### ISSUE TITLE
bad repo name

### ISSUE THREAD

**Issue by dwalker-va** [vendasta/sso-php-sdk#1]
`vendasta-sso-php-sdk` or
`vendasta-sso-sdk-php`
@byates-va

**Comment by cgooding-va** [comment]
What about `sdk-sso-vendasta-php`

**Comment by dwalker-va** [comment]
sounds like something @byates considered, but no

**Comment by bjohnson-va** [comment]
If this SDK were a php object, it would be: `$vendasta->sso->sdk->php`

**Comment by brentyates** [comment]
I was following the other existing PHP SDK repos we have as convention... gawd.

**Comment by dwalker-va** [comment]
like a lemming off a cliff

**Comment by brentyates** [comment]
I like lemmings

**Comment by brentyates** [comment]
oh em gee it can be played online nowadays http://www.crazygames.com/game/html5-lemmings

**Comment by brentyates** [comment]
Renamed.
